# Generated by Django 3.2.8 on 2022-02-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(default='default_profile_image.jpg', upload_to='profile_images'),
        ),
    ]
