# Generated by Django 4.0.2 on 2022-03-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_post_is_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default_post_image.jpg', upload_to='post_images'),
        ),
    ]
