# Generated by Django 4.0.2 on 2022-03-03 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_profile_image'),
        ('forum', '0005_post_image'),
    ]

    operations = [
    ]
