# Generated by Django 4.0.2 on 2022-03-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_merge_0005_alter_profile_image_0005_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_profile_image.png', upload_to='profile_images'),
        ),
    ]
