# Generated by Django 4.0.2 on 2022-03-10 13:34

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(default='no_description', max_length=1024, verbose_name='Beskrivelse'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default_post_image.jpg', upload_to='post_images', verbose_name='Bilde'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_sale',
            field=models.BooleanField(verbose_name='Salgs annonse'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='Solgt'),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Pris'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tittel'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_profile_image.png', upload_to='profile_images', verbose_name='Bilde'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='Telefonnummer'),
        ),
    ]
