# Generated by Django 3.2.8 on 2022-03-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_alter_post_description_alter_post_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(max_length=11, verbose_name='Telefonnummer'),
        ),
    ]
