# Generated by Django 4.0.2 on 2022-03-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_remove_rating_user_rating_rated_by_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='is_seller_rating_buyer',
            field=models.BooleanField(default=False, verbose_name='Er det selger som vurderer kjøper?'),
        ),
        migrations.AddField(
            model_name='rating',
            name='rated_user_responded',
            field=models.BooleanField(default=False, verbose_name='Vurdert bruker har vurdert tilbake?'),
        ),
    ]
