# Generated by Django 3.2.12 on 2022-03-24 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_post_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='location',
        ),
        migrations.RemoveField(
            model_name='post',
            name='type',
        ),
    ]
