# Generated by Django 4.0.2 on 2022-03-24 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_alter_profile_phone'),
        ('forum', '0012_rating_post'),
    ]

    operations = [
    ]
