# Generated by Django 3.2.12 on 2022-03-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_auto_20220324_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default='location', max_length=1024, verbose_name='Lokasjon'),
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(default='location', max_length=1024, verbose_name='Type'),
        ),
    ]
