# Generated by Django 4.0.2 on 2022-03-24 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_merge_0011_alter_profile_phone_0012_rating_post'),
        ('forum', '0014_auto_20220324_1224'),
    ]

    operations = [
    ]
